version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: airlabs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airlabsdb
      MYSQL_USER: airlabs
      MYSQL_PASSWORD: 0101
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: minhtoan0101/airlabs-project:latest
    container_name: airlabs-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
